import {useEffect,useState} from 'react'
import {Info,Check,ArrowRight} from 'lucide-react'
import {useStore} from '../store'
import type {Asset} from '../types'
import {Badge,Button,Modal} from './UI'
import {Link} from 'react-router-dom'
export function ReviewInspector({asset,onReviewed}:{asset:Asset;onReviewed?:()=>void}){const {setState,toast}=useStore(),[adapted,setAdapted]=useState(asset.adapted),[why,setWhy]=useState(asset.why),[reject,setReject]=useState(false),[reason,setReason]=useState('')
useEffect(()=>{setAdapted(asset.adapted);setWhy(asset.why);setReason('')},[asset.id])
function review(status:'approved'|'rejected'){setState(s=>{const assets=s.assets.map(a=>a.id===asset.id?{...a,status,adapted,why,reviewNote:reason}:a);return {...s,assets,sessions:s.sessions.map(session=>session.id===asset.sessionId?{...session,status:assets.some(a=>a.sessionId===session.id&&a.status==='pending')?'review':'complete'}:session)}});setReject(false);toast(status==='approved'?'已批准入库，可在话术学习库查看':'已标记不入库，保留原话和审核记录');onReviewed?.()}
return <aside className="review-inspector"><div className="inspector-heading"><h2>审核候选话术</h2><Badge tone={asset.status==='pending'?'amber':asset.status==='approved'?'green':'neutral'}>{{pending:'待审核',approved:'已入库',rejected:'不入库',withdrawn:'已撤回'}[asset.status]}</Badge></div><div className="inline-field"><b>话术分类</b><Badge tone="teal">{asset.category}</Badge></div><label className="field"><b>主播原话</b><div className="readonly-quote">{asset.quote}</div></label><label className="field"><b>教学说明</b><textarea aria-label="教学说明" value={why} readOnly={asset.status!=='pending'} onChange={e=>setWhy(e.target.value)} rows={3}/></label><div className="field"><b>适用场景</b><p>{asset.condition}</p></div><label className="field"><b>适配示例</b><textarea aria-label="适配示例" value={adapted} onChange={e=>setAdapted(e.target.value)} rows={3} maxLength={1000} readOnly={asset.status!=='pending'}/></label><p className="helper"><Info size={15}/>原话保留，适配稿单独保存</p>{asset.reviewNote&&<p className="muted">审核备注：{asset.reviewNote}</p>}<div className="inspector-actions">{asset.status==='pending'?<><Button onClick={()=>setReject(true)}>不入库</Button><Button primary onClick={()=>review('approved')}><Check size={16}/>批准入库</Button></>:asset.status==='approved'?<Link to={'/library?asset='+asset.id} className="button primary full">在学习库查看<ArrowRight size={16}/></Link>:<Button onClick={()=>{setState(s=>({...s,assets:s.assets.map(a=>a.id===asset.id?{...a,status:'pending'}:a),sessions:s.sessions.map(session=>session.id===asset.sessionId?{...session,status:'review'}:session)}));toast('已重新打开审核')}}>重新审核</Button>}</div><Modal open={reject} onOpenChange={setReject} title="这条话术暂不入库" description="保留原话和来源，记录本次审核判断。"><label className="field">原因（选填）<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="例如：内容较普通，缺少可迁移的方法"/></label><div className="modal-footer"><Button onClick={()=>setReject(false)}>继续修改</Button><Button primary onClick={()=>review('rejected')}>确认不入库</Button></div></Modal></aside>}
