import {NavLink,Outlet,Link} from 'react-router-dom'
import {House,Video,FileText,ClipboardCheck,BookOpen,CalendarCheck,Settings,Bell,ChevronRight,UserRound,Menu,RotateCcw} from 'lucide-react'
import {useState} from 'react'
import {useStore} from '../store'
import {IconButton,Modal,Button} from './UI'
const nav=[['/','工作台',House],['/sessions','直播场次',Video],['/weekly','主播周总结',FileText],['/reports','总结报告',FileText],['/reviews','话术审核',ClipboardCheck],['/library','话术学习库',BookOpen],['/plans','备播计划',CalendarCheck],['/settings','设置',Settings]] as const
export function Shell(){const {state,reset}=useStore(),[menu,setMenu]=useState(false),[notifications,setNotifications]=useState(false),[resetOpen,setResetOpen]=useState(false)
const pending=state.assets.filter(a=>a.status==='pending').length
return <div className="app-shell"><aside className={`sidebar ${menu?'mobile-open':''}`}><Link to="/" className="brand" onClick={()=>setMenu(false)}><img src="/assets/brand.png" alt=""/><div><strong>{state.workspace}</strong><span>资产工作台</span></div></Link><nav aria-label="主导航">{nav.map(([url,label,Icon])=><NavLink key={url} to={url} end={url==='/'} onClick={()=>setMenu(false)}><Icon size={21}/><span>{label}</span></NavLink>)}</nav><button className="account" onClick={()=>setResetOpen(true)}><span className="avatar"><UserRound size={20}/></span><b>管理员</b><ChevronRight size={17}/></button></aside>{menu&&<button aria-label="关闭导航" className="mobile-scrim" onClick={()=>setMenu(false)}/>}
<div className="app-body"><header className="topbar"><div className="mobile-menu"><IconButton label="打开导航" onClick={()=>setMenu(!menu)}><Menu size={21}/></IconButton></div><span className="top-context">工作区 <ChevronRight size={13}/> 自有直播</span><div className="top-actions"><IconButton label="通知" onClick={()=>setNotifications(true)}><Bell size={19}/>{pending>0&&<i className="notification-dot"/>}</IconButton><span className="prototype-badge">原型 · 示例内容</span></div></header><main className="main"><Outlet/></main></div>
<Modal open={notifications} onOpenChange={setNotifications} title="工作区通知" description="根据当前示例操作更新待办。"><div className="notice-row"><ClipboardCheck/><div><b>{pending} 条候选话术等待审核</b><p className="muted">审核通过后可供新主播学习和备播。</p></div></div><Link to="/reviews" className="button primary" onClick={()=>setNotifications(false)}>前往话术审核</Link></Modal>
<Modal open={resetOpen} onOpenChange={setResetOpen} title="原型演示" description="所有操作仅作用于本次浏览器演示，刷新页面会恢复初始示例。"><p>原型未连接后端、模型或 PostgreSQL，未处理真实直播数据。</p><Button onClick={()=>{reset();setResetOpen(false)}}><RotateCcw size={16}/>重置示例数据</Button></Modal></div>}
