import * as Dialog from '@radix-ui/react-dialog'
import {X,Search,Inbox} from 'lucide-react'
import type {ReactNode} from 'react'
export function Button({children,primary=false,className='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{primary?:boolean}){return <button className={`button ${primary?'primary':''} ${className}`} {...props}>{children}</button>}
export function IconButton({label,children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){return <button type="button" className="icon-button" aria-label={label} title={label} {...props}>{children}</button>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
export function PageHeader({title,description,actions,eyebrow}:{title:string;description?:string;actions?:ReactNode;eyebrow?:string}){return <div className="page-heading"><div>{eyebrow&&<div className="breadcrumb">{eyebrow}</div>}<h1>{title}</h1>{description&&<p className="subtitle">{description}</p>}</div>{actions&&<div className="actions">{actions}</div>}</div>}
export function SearchInput({value,onChange,placeholder='搜索'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="search"><Search size={18}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="清除搜索" onClick={()=>onChange('')}><X size={15}/></button>}</label>}
export function Modal({open,onOpenChange,title,description,children}:{open:boolean;onOpenChange:(open:boolean)=>void;title:string;description?:string;children:ReactNode}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal"><div className="modal-title"><Dialog.Title>{title}</Dialog.Title><Dialog.Close asChild><IconButton label="关闭"><X size={20}/></IconButton></Dialog.Close></div><Dialog.Description className="muted">{description||'填写信息后继续。'}</Dialog.Description>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export function Empty({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="empty"><Inbox size={32}/><h3>{title}</h3><p>{description}</p>{action}</div>}
export function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
