import {useState} from 'react'
import {Link} from 'react-router-dom'
import {Plus,Upload,FileText,ClipboardCheck,CalendarDays,ArrowRight,Circle,CheckCheck} from 'lucide-react'
import {useStore} from '../store'
import {PageHeader,Button} from '../components/UI'
import {SessionTable} from '../components/SessionTable'
import {NewSession} from '../components/NewSession'
export function Dashboard(){const {state}=useStore(),[create,setCreate]=useState(false),[host,setHost]=useState('全部主播'),[week,setWeek]=useState('本周 · 9月28日—10月4日');const sessions=state.sessions.filter(s=>(host==='全部主播'||s.host===host)&&(week.startsWith('本周')?s.date>='2026-09-28'&&s.date<='2026-10-04':s.date<'2026-09-28'));const summarySessions=sessions.filter(s=>s.host===(host==='全部主播'?'大魏':host));const pending=state.assets.filter(a=>a.status==='pending'&&sessions.some(s=>s.id===a.sessionId));const steps=[['导入直播','上传录制内容，生成待复盘场次',Upload,'/sessions'],['单场复盘','梳理重点内容与问题片段',FileText,'/demo/sessions/s1'],['审核话术','筛选可复用表达，确认修改',ClipboardCheck,'/reviews'],['下一场备播','基于复盘结果，编排备播计划',CalendarDays,'/plans']] as const
return <><PageHeader title="工作台" description="先完成复盘，再准备下一场。" actions={<><select aria-label="选择周次" value={week} onChange={e=>setWeek(e.target.value)}><option>本周 · 9月28日—10月4日</option><option>上周 · 9月21日—9月27日</option></select><select aria-label="筛选主播" value={host} onChange={e=>setHost(e.target.value)}><option>全部主播</option><option>大魏</option><option>小林</option></select><Button primary onClick={()=>setCreate(true)}><Plus size={18}/>新建直播场次</Button></>}/>
<div className="workflow-strip">{steps.map(([title,desc,Icon,path],i)=><div className="workflow-step" key={title}><Link to={path}><span className="step-icon"><Icon size={25}/></span><div><strong>{title}</strong><small>{desc}</small></div></Link>{i<3&&<ArrowRight className="step-arrow" size={21}/>}</div>)}</div>
<div className="metrics"><div><span>{week.startsWith('本周')?'本周直播':'上周直播'}</span><strong>{sessions.length}<small>场</small></strong></div><Link to="/reviews"><span>待审核话术</span><strong>{pending.length}<small>条</small></strong></Link><Link to="/plans"><span>待完成备播</span><strong>{state.plans.filter(p=>p.status==='draft').length}<small>份</small></strong></Link><small className="sample-label">示例数据</small></div>
<div className="dashboard-columns"><section className="panel"><div className="panel-heading"><h2>最近直播</h2><Link className="text-link" to="/sessions">查看全部场次<ArrowRight size={16}/></Link></div><SessionTable sessions={sessions.slice(0,3)}/></section><section className="panel weekly-card"><h2>{host==='全部主播'?'大魏':host} · 周总结</h2><p className="muted">{week.split(' · ')[1]}</p>{summarySessions.length>0?[{label:'重复问题',text:'开场铺垫较长'},{label:'可复用表达',text:'先回应家长困惑，再解释方法'},{label:'下周行动',text:'压缩开场，提前安排互动'}].map(row=><div className="weekly-line" key={row.label}><p><b>{row.label}：</b>{row.text}</p><small>关联 {summarySessions.length} 场直播</small></div>):<p className="muted">所选主播在这一周暂无直播记录</p>}<Link className="button full" to="/weekly">查看完整周总结</Link><div className="pending-score"><FileText size={25}/><div><strong>评分配置待确认</strong><p>先查看复盘结论与原话依据</p></div></div></section></div>
<section className="panel next-step"><h2>下一步</h2><div>{pending.length?<Circle size={20}/>:<CheckCheck size={20}/>}<p>{pending.length?`审核 ${pending.length} 条候选话术`:'本周话术已审核，可以准备下一场直播'}</p><Link className="button primary" to={pending.length?'/reviews':'/plans'}>{pending.length?'去审核':'去备播'}</Link></div></section><NewSession open={create} onOpenChange={setCreate}/></>}
