import {useState} from 'react'
import {Link,useNavigate,useSearchParams} from 'react-router-dom'
import {ArrowUpRight,Check,Download,FileText,Info,Settings2,Printer,ArrowRight} from 'lucide-react'
import {useStore} from '../store'
import {Badge,Button,Empty,Modal,PageHeader,download} from '../components/UI'
import {escapeHtml} from '../components/AddToPlan'
import type {ReportDraft} from '../types'

const chapters=[['overview','报告总览'],['strengths','亮点与原话依据'],['issues','问题与待核实项'],['expression','表达与节奏观察'],['assets','可学习的话术'],['actions','下一场行动计划'],['sources','来源与报告说明']] as const
const initialDraft=():ReportDraft=>({
 summary:'本次复盘先聚焦一个练习方向：将笼统的评价转为具体问题，再给出可尝试的小行动。以下为结构示例，需结合完整直播回看后修订。',
 strengths:'值得保留的表达方式：先接住家长的困惑，再定位孩子具体卡住的一步。复用时应保留适用条件，避免将表达技巧当作效果承诺。',
 issues:'待回看：是否在开场及时讲清本场能解决的问题？方法讲解之后是否留出回应空间？目前只展示局部原话，尚不足以判断整场节奏或互动效果。',
 actions:'下一场先选一个具体问题开场；讲完一个方法后邀请观众描述自己的情况；结束时留下一项可以尝试的小练习。',
 owner:'主播本人',check:'回看下一场的开场、方法讲解和收尾，核对是否实际执行；效果需另行结合观众反馈判断。',
 visible:['overview','strengths','issues','expression','assets','actions','sources'],version:1,confirmed:false
})

export function Reports(){
 const {state,setState,toast}=useStore(),[params,setParams]=useSearchParams(),navigate=useNavigate()
 const mode=params.get('mode')==='single'?'single':'weekly'
 const host=params.get('host')||'大魏',from=params.get('from')||'2026-09-28',to=params.get('to')||'2026-10-04'
 const sessionId=params.get('session')||'s1'
 const sessions=state.sessions.filter(s=>s.status!=='draft'&&(mode==='single'?s.id===sessionId:s.host===host&&s.date>=from&&s.date<=to))
 const assets=state.assets.filter(a=>sessions.some(s=>s.id===a.sessionId)),approved=assets.filter(a=>a.status==='approved')
 const reportHost=mode==='single'?sessions[0]?.host||'主播':host
 const title=mode==='single'?`${sessions[0]?.title||'单场直播'} · 总结报告`:`${reportHost} · 直播周总结报告`
 const range=mode==='single'?sessions[0]?.date||'':`${from} — ${to}`
 const key=mode==='single'?`single:${sessionId}`:`weekly:${host}:${from}:${to}`
 const draft=state.reportDrafts[key]||initialDraft()
 const signature=JSON.stringify({sessions,assets}),confirmed=draft.confirmed&&draft.sourceSignature===signature
 const [editing,setEditing]=useState(false),[working,setWorking]=useState<ReportDraft>(draft),[config,setConfig]=useState(false),[confirm,setConfirm]=useState(false),[exportText,setExportText]=useState('')
 const evidence=assets[0]
 function change(values:Record<string,string>){const next=new URLSearchParams(params);Object.entries(values).forEach(([k,v])=>next.set(k,v));setParams(next)}
 function save(next:ReportDraft){setState(s=>({...s,reportDrafts:{...s.reportDrafts,[key]:next}}))}
 function edit(){setWorking({...draft});setEditing(true)}
 function plan(){const id=crypto.randomUUID();setState(s=>({...s,plans:[...s.plans,{id,title:`${mode==='single'?sessions[0].title:reportHost+'直播'} · 复盘后备播`,host:reportHost,date:new Date(Date.now()+86400000).toLocaleDateString('sv-SE'),status:'draft',sections:[{id:crypto.randomUUID(),title:'复盘行动落实',minutes:5,goal:'落实总结报告中的下一场行动',html:`<p>${escapeHtml(draft.actions).replaceAll('\n','</p><p>')}</p>`,prompt:draft.check,assetIds:[]}]}]}));toast('行动计划已带入新备播草稿，请补充本场表达');navigate('/plans/'+id)}
 function exportReport(){
 const content:Record<string,string>={overview:draft.summary,strengths:draft.strengths+(evidence?`\n\n原话示例：${evidence.quote}\n来源：${evidence.host} / ${evidence.date} / ${evidence.time} / 场次 ${evidence.sessionId}`:'\n暂无原话依据'),issues:draft.issues,expression:'语速、停顿、口头禅、镜头表现：未接入分析。评分标准与阈值待确认，不计算综合分。',assets:approved.length?approved.map(a=>`- 原话：${a.quote}\n  教学说明：${a.why}\n  适配示例：${a.adapted}\n  来源：${a.host} / ${a.date} / ${a.time} / ${a.sessionId}`).join('\n'):'暂无已审核资产。',actions:`行动：${draft.actions}\n负责人：${draft.owner}\n回看核验：${draft.check}`,sources:sessions.map(s=>`- ${s.title} / ${s.host} / ${s.date} / ${s.id}`).join('\n')+'\n\n结构参考：路演评分报告_会议3 (13).pdf。仅借鉴报告组织方式，不采用其中评分、阈值或结论。所有直播内容为原型示例；原话、解释、建议分别保留。'}
 setExportText(`# ${title}\n\n${range} · v${draft.version} · ${confirmed?'已人工确认（示例）':'待人工复核'}\n\n> 前端原型示例，不是实际分析报告。\n\n`+chapters.filter(([id])=>draft.visible.includes(id)).map(( [id,label])=>`## ${label}\n\n${content[id]}`).join('\n\n'))
 }
 return <div className="reports-page"><PageHeader title="总结报告" description="把复盘结论、原话依据和下一场行动，整理成一份可审阅的报告。" actions={<><Button onClick={()=>setConfig(true)}><Settings2 size={16}/>报告模板</Button><Button onClick={exportReport} disabled={!sessions.length}><Download size={16}/>导出报告</Button><Button onClick={()=>window.print()} disabled={!sessions.length}><Printer size={16}/>打印 / PDF</Button></>}/>
 <form className="toolbar report-filters" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);change({from:String(data.get('from')),to:String(data.get('to'))})}}><div className="segmented">{[['weekly','主播周报'],['single','单场报告']].map(([value,label])=><button type="button" key={value} className={mode===value?'selected':''} onClick={()=>change({mode:value})}>{label}</button>)}</div>{mode==='weekly'?<><select aria-label="报告主播" value={host} onChange={e=>change({host:e.target.value})}>{Array.from(new Set(state.sessions.map(s=>s.host))).map(h=><option key={h}>{h}</option>)}</select><label>从 <input name="from" aria-label="报告开始日期" type="date" value={from} onChange={e=>change({from:e.target.value})}/></label><label>至 <input name="to" aria-label="报告结束日期" type="date" value={to} onChange={e=>change({to:e.target.value})}/></label><Button type="submit">更新范围</Button></>:<select aria-label="报告场次" value={sessionId} onChange={e=>change({session:e.target.value})}>{state.sessions.filter(s=>s.status!=='draft').map(s=><option value={s.id} key={s.id}>{s.date} · {s.title} · {s.host}</option>)}</select>}</form>
 {!sessions.length?<Empty title={from>to&&mode==='weekly'?'开始日期不能晚于结束日期':'当前范围没有可复盘的直播'} description="选择已导入示例结果的场次，或调整主播与日期范围。" action={<Link className="button" to="/sessions">查看直播场次</Link>}/>:<div className="summary-layout"><aside className="summary-nav"><span className="eyebrow-text">REPORT CONTENTS</span><h2>报告目录</h2>{chapters.filter(([id])=>draft.visible.includes(id)).map(([id,label],i)=><a href={'#report-'+id} key={id}><small>{String(i+1).padStart(2,'0')}</small>{label}</a>)}<div className="summary-note"><Info size={18}/><p>参考模板 v0.1<br/>章节可调整<br/>评分标准待确认</p></div></aside>
 <article className="summary-document"><header className="summary-cover"><div className="summary-kicker"><span>LIVE REVIEW / 复盘报告</span><Badge tone={confirmed?'green':'amber'}>{confirmed?'已人工确认 · 示例':'待人工复核'}</Badge></div><h2>{title}</h2><p className="muted">{range}　·　{reportHost}　·　v{draft.version}</p><div className="summary-counts"><div><strong>{sessions.length}</strong><span>关联直播</span></div><div><strong>{approved.length}</strong><span>已审核话术</span></div><div><strong>{assets.filter(a=>a.status==='pending').length}</strong><span>待审核候选</span></div><div><strong className="pending-label">待确认</strong><span>评分标准</span></div></div><p className="report-disclaimer">示例报告 · 尚未分析真实直播 · 编辑仅保留在本次页面会话</p></header>
 <section id="report-overview" className="summary-section"><div className="summary-section-title"><h3><span>01</span>报告总览</h3><Button onClick={edit}>编辑报告内容</Button></div><p className="summary-lead">{draft.summary}</p></section>
 {draft.visible.includes('strengths')&&<section id="report-strengths" className="summary-section"><h3>亮点与原话依据</h3><p>{draft.strengths}</p>{evidence?<div className="report-evidence"><Badge tone="teal">原话示例 · 需回看上下文</Badge><blockquote>“{evidence.quote}”</blockquote><Link className="text-link" to={`/demo/sessions/${evidence.sessionId}?at=${evidence.seconds}`}>{evidence.host} · {evidence.date} · {evidence.time}<ArrowUpRight size={15}/></Link></div>:<p className="muted">暂无可引用原话。请补充来源后再作判断。</p>}</section>}
 {draft.visible.includes('issues')&&<section id="report-issues" className="summary-section"><h3>问题与待核实项</h3><Badge tone="amber">观察建议 · 不是已证实的结论</Badge><p className="report-paragraph">{draft.issues}</p><div className="report-footnote">局部片段不能代表整场；没有观众或经营数据时，不推断留存、转化或成交效果。</div></section>}
 {draft.visible.includes('expression')&&<section id="report-expression" className="summary-section"><h3>表达与节奏观察</h3><p className="muted">先保留观察位置，接入材料与规则后再填写。</p><div className="report-observations">{['语速与停顿','口头表达','镜头与动作','互动与回应'].map(name=><div key={name}><b>{name}</b><Badge>未分析</Badge><small>需要原始材料及统计口径</small></div>)}</div><p className="report-footnote">未采用参考报告中的理想语速、音视频融合分或能力画像；长期画像放在后续阶段。</p></section>}
 {draft.visible.includes('assets')&&<section id="report-assets" className="summary-section"><div className="summary-section-title"><h3>可学习的话术</h3><Link className="text-link" to="/reviews">处理待审核候选<ArrowRight size={15}/></Link></div><p className="muted">只展示已批准资产；原话、教学说明和适配示例分别保存。</p>{approved.length?approved.slice(0,3).map(a=><div className="report-asset" key={a.id}><Badge tone="green">{a.category} · 已入库</Badge><blockquote>{a.quote}</blockquote><p><b>学习要点：</b>{a.why}</p><Link className="text-link" to={'/library?asset='+a.id}>查看教学说明与适配示例<ArrowUpRight size={15}/></Link></div>):<p>暂无已审核话术，请先完成人工审核。</p>}{approved.length>3&&<Link className="text-link" to="/library">还有 {approved.length-3} 条，前往学习库查看（导出包含全部）</Link>}</section>}
 {draft.visible.includes('actions')&&<section id="report-actions" className="summary-section"><h3>下一场行动计划</h3><div className="report-action"><Badge tone="teal">优先练习 · 可调整</Badge><p className="report-paragraph">{draft.actions}</p><dl><dt>负责人</dt><dd>{draft.owner}</dd><dt>执行时间</dt><dd>下一场直播前备稿，直播后回看</dd><dt>如何核验</dt><dd>{draft.check}</dd></dl><Button primary onClick={plan}>带入下一场备播<ArrowRight size={16}/></Button><small>新建一份备播草稿，带入行动与核验提示；不会自动批准候选话术。</small></div></section>}
 <section id="report-sources" className="summary-section"><h3>来源与报告说明</h3>{sessions.map(s=><Link key={s.id} className="weekly-source" to={'/demo/sessions/'+s.id}><span>{s.title}</span><small>{s.host} · {s.date}<ArrowUpRight size={14}/></small></Link>)}<p className="report-footnote">结构参考《路演评分报告_会议3 (13).pdf》的总览、问题分析、依据和行动计划。这里展示的是直播复盘模板，不沿用路演评分模型。所有内容均为原型示例。</p></section>
 <footer className="summary-footer"><span>{confirmed?'本版本已人工确认；内容修改后需再次确认。':'建议先核对原话与建议，再确认报告。'}</span><Button primary onClick={()=>setConfirm(true)} disabled={confirmed}><Check size={16}/>{confirmed?'报告已确认':'确认本版报告'}</Button></footer></article></div>}
 <Modal open={!!exportText} onOpenChange={v=>{if(!v)setExportText('')}} title="导出报告" description="导出包含所选章节及全部已审核话术，格式为 Markdown。也可以直接复制全文。"><label className="field">报告正文<textarea aria-label="导出报告正文" readOnly value={exportText} rows={14}/></label><div className="modal-footer"><Button onClick={()=>navigator.clipboard.writeText(exportText).then(()=>toast('已复制报告全文')).catch(()=>toast('复制未完成，请在正文框手动选择复制'))}>复制全文</Button><Button primary onClick={()=>download(title+'.md',exportText)}>下载 Markdown</Button></div></Modal>
 <Modal open={editing} onOpenChange={setEditing} title="编辑总结报告" description="修改复盘解释和行动建议，保留来源原话。保存后需重新确认。"><form onSubmit={e=>{e.preventDefault();save({...working,version:draft.version+1,confirmed:false});setEditing(false);toast('已保存报告修订，本版本待人工复核')}}>{([['summary','报告总览'],['strengths','亮点说明'],['issues','问题与待核实项'],['actions','下一场行动'],['owner','负责人'],['check','核验方式']] as const).map(([field,label])=><label className="field" key={field}>{label}<textarea required rows={field==='owner'?1:3} value={working[field]} onChange={e=>setWorking(w=>({...w,[field]:e.target.value}))}/></label>)}<div className="modal-footer"><Button type="button" onClick={()=>setEditing(false)}>取消</Button><Button primary type="submit">保存报告修订</Button></div></form></Modal>
 <Modal open={config} onOpenChange={setConfig} title="报告模板 · 试用版" description="先用这套结构讨论，不代表评分标准已经确定。配置作用于当前报告。"><div className="report-template-options">{chapters.map(([id,label])=><label key={id}><input type="checkbox" checked={draft.visible.includes(id)} disabled={id==='overview'||id==='sources'} onChange={e=>save({...draft,visible:e.target.checked?[...draft.visible,id]:draft.visible.filter(x=>x!==id),confirmed:false,version:draft.version+1})}/>{label}{(id==='overview'||id==='sources')&&<small>必选</small>}</label>)}</div><div className="callout"><Info size={19}/><span>维度、权重、分数阈值与长期画像均未启用。</span></div><div className="modal-footer"><Button primary onClick={()=>setConfig(false)}>完成</Button></div></Modal>
 <Modal open={confirm} onOpenChange={setConfirm} title="确认当前报告" description="确认表示已审阅本次示例报告，不代表系统验证了事实或模型结果。"><p>请核对原话来源、待核实问题及下一场行动。后续修改会恢复待复核状态。</p><div className="modal-footer"><Button onClick={()=>setConfirm(false)}>继续检查</Button><Button primary onClick={()=>{save({...draft,confirmed:true,sourceSignature:signature});setConfirm(false);toast('本版本报告已人工确认')}}>确认已审阅</Button></div></Modal>
 </div>
}
