import {useState} from 'react'
import {Link} from 'react-router-dom'
import {CheckCheck,ArrowUpRight} from 'lucide-react'
import {useStore} from '../store'
import {PageHeader,Badge,SearchInput,Empty} from '../components/UI'
import {ReviewInspector} from '../components/ReviewInspector'
import {MediaPreview} from '../components/MediaPreview'
export function Reviews(){const {state}=useStore(),[status,setStatus]=useState('pending'),[query,setQuery]=useState(''),[selected,setSelected]=useState('');const assets=state.assets.filter(a=>a.status===status&&(a.quote+a.host).includes(query)),asset=assets.find(a=>a.id===selected)||assets[0]
return <><PageHeader title="话术审核" description="核对原话、完善教学说明，把真正值得学习的内容留下来。" actions={<Badge tone="amber">{state.assets.filter(a=>a.status==='pending').length} 条待审核</Badge>}/><div className="toolbar"><div className="segmented">{[['pending','待审核'],['approved','已入库'],['rejected','不入库']].map(([s,l])=><button className={status===s?'selected':''} key={s} onClick={()=>{setStatus(s);setSelected('')}}>{l}<span>{state.assets.filter(a=>a.status===s).length}</span></button>)}</div><SearchInput value={query} onChange={setQuery} placeholder="搜索原话或主播"/></div>{asset?<div className="queue-layout"><section className="review-queue">{assets.map(a=><button key={a.id} className={a.id===asset.id?'selected':''} onClick={()=>setSelected(a.id)}><Badge tone="teal">{a.category}</Badge><p>“{a.quote}”</p><small>{a.host} · {a.date.slice(5)} · {a.time}</small></button>)}</section><section className="queue-source"><h2>原话与来源</h2><MediaPreview compact seconds={asset.seconds}/><blockquote>{asset.quote}</blockquote><Link className="text-link" to={`/sessions/${asset.sessionId}?at=${asset.seconds}`}>进入场次查看完整上下文<ArrowUpRight size={15}/></Link><div className="callout"><CheckCheck size={20}/><span>原话始终保留，审核修改作用于教学说明和适配示例。</span></div></section><ReviewInspector asset={asset}/></div>:<Empty title={query?'没有匹配的话术':'这一组已处理完毕'} description="切换审核状态，或到学习库查看已批准的内容。" action={<Link className="button primary" to="/library">查看话术学习库</Link>}/>}</>}
