import {useEffect,useState} from 'react'
import {Link,useParams,useSearchParams} from 'react-router-dom'
import {Download,Check,ClipboardCheck,Info,Upload,FileText,Play,ArrowRight,Plus} from 'lucide-react'
import {useStore} from '../store'
import {transcript} from '../data'
import {PageHeader,Button,Badge,Empty,SearchInput,download} from '../components/UI'
import {MediaPreview} from '../components/MediaPreview'
import {ReviewInspector} from '../components/ReviewInspector'
export function SessionDetail(){const {id}=useParams(),[params]=useSearchParams(),{state,setState,toast}=useStore(),[tab,setTab]=useState('录像与逐字稿'),[query,setQuery]=useState(''),[time,setTime]=useState(Number(params.get('at'))||754),[selected,setSelected]=useState(''),[fileUrl,setFileUrl]=useState('')
const session=state.sessions.find(s=>s.id===id),assets=state.assets.filter(a=>a.sessionId===id),asset=assets.find(a=>a.id===selected)||assets.find(a=>a.status==='pending')||assets[0];useEffect(()=>()=>{if(fileUrl)URL.revokeObjectURL(fileUrl)},[fileUrl]);if(!session)return <Empty title="场次不存在" action={<Link to="/sessions">返回直播场次</Link>}/>
const pending=assets.filter(a=>a.status==='pending').length
function example(){const template=state.assets.find(a=>a.id==='p0')||state.assets[0];setState(s=>({...s,sessions:s.sessions.map(x=>x.id===id?{...x,status:'review',duration:'56:20',material:'示例复盘材料'}:x),assets:[...s.assets,{...template,id:crypto.randomUUID(),sessionId:id!,host:session!.host,date:session!.date,status:'pending'}]}));toast('已载入示例复盘；未分析所选本地文件')}
const report=`${session.title} · 单场复盘（示例）\n\n整体观察\n能够回应家长焦虑，讲解具体；开场信息较多，可更早明确本场要解决的问题。\n\n可保留表达\n${asset?.quote||'暂无'}\n\n下一场行动\n用一个具体问题开场；每讲完一个方法，安排一次互动。\n\n评分：规则待确认，未生成分数。`
return <><PageHeader title={session.title} eyebrow="直播场次 / 场次详情" description={`${session.host} · ${session.date.slice(5).replace('-','月')}日 · 自有直播`} actions={<>{session.status!=='draft'&&<Link className="button" to={'/reports?mode=single&session='+session.id}>总结报告</Link>}<Button disabled={session.status==='draft'} onClick={()=>download(session.title+'-示例复盘.txt',report)}><Download size={17}/>导出复盘</Button><Button primary disabled={session.status==='draft'} onClick={()=>{setTab('录像与逐字稿');document.getElementById('review-area')?.scrollIntoView({behavior:'smooth',block:'center'})}}><ClipboardCheck size={17}/>审核候选话术</Button></>}/>
{session.status==='draft'?<section className="panel import-panel"><Upload size={38}/><h2>添加本场直播材料</h2><p className="muted">选择录像、逐字稿或 PDF，体验材料登记。文件不会上传。</p><label className="button primary"><Plus size={17}/>选择本地材料<input type="file" accept="video/*,.txt,.srt,.pdf,.json" hidden onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.type.startsWith('video/'))setFileUrl(URL.createObjectURL(f));setState(s=>({...s,sessions:s.sessions.map(x=>x.id===id?{...x,material:f.name}:x)}));toast('已选择文件，仅用于本次原型预览')}}/></label>{session.material&&<p className="selected-file"><FileText size={17}/>{session.material}<Badge>本地选择</Badge></p>}{fileUrl&&<video controls src={fileUrl} className="local-video"/>}<hr/><p>暂未接入转写与分析，可以先体验预先准备的示例结果。</p><Button onClick={example}>使用示例材料体验复盘<ArrowRight size={16}/></Button></section>:<><div className="progress-steps">{['材料已导入','复盘已生成',pending?'话术待审核':'话术已审核',session.status==='prepared'?'备播稿已形成':'备播待形成'].map((s,i)=><div key={i} className={i<2||i===2&&!pending?'done':i===2?'current':''}><span>{i<2||i===2&&!pending?<Check size={15}/>:i+1}</span>{s}{i<3&&<i/>}</div>)}</div>
<div className="tabs" role="tablist">{['录像与逐字稿','复盘报告','评分（待配置）','候选话术'].map(t=><button role="tab" aria-selected={tab===t} className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t}{t==='候选话术'&&<span className="count">{assets.length}</span>}</button>)}</div>
{tab==='录像与逐字稿'&&<div className="review-grid" id="review-area"><section className="review-media"><MediaPreview seconds={time} onSeek={setTime}/><h2>这段话为什么值得保留</h2><p>{asset?.why||'当前片段没有候选话术。'}</p><button className="text-link" onClick={()=>setTab('复盘报告')}>查看报告中的关联分析<ArrowRight size={16}/></button></section><section className="transcript-panel"><div className="section-title"><h2>逐字稿</h2><small>点击时间，回看原片段</small></div><SearchInput value={query} onChange={setQuery} placeholder="搜索原话"/><div className="transcript-list">{transcript.filter(t=>t.text.includes(query)).map(t=><button className={'transcript-row '+(time>=t.seconds&&time<(transcript[transcript.indexOf(t)+1]?.seconds??Infinity)?'active':'')} onClick={()=>setTime(t.seconds)} key={t.time}><time>{t.time}</time><span>{t.text}</span>{time===t.seconds&&<Play size={15} fill="currentColor"/>}</button>)}{!transcript.some(t=>t.text.includes(query))&&<Empty title="没有匹配的原话"/>}</div></section>{asset?<ReviewInspector asset={asset}/>:<Empty title="本场暂无候选"/>}</div>}
{tab==='复盘报告'&&<div className="report-layout"><article className="panel report-document"><Badge>单场复盘 · 示例</Badge><h2>{session.title}</h2><p className="muted">{session.host} · {session.date} · {session.duration}</p><h3>01 整体观察</h3><p>本场以回应家长的具体困惑为主，表达亲和，能够把问题拆成可操作的小步骤。开场铺垫较长，可更早明确今晚的核心问题。</p><h3>02 值得保留的表达</h3><blockquote>{asset?.quote}</blockquote><button className="text-link" onClick={()=>{setTab('录像与逐字稿');setTime(asset?.seconds||754)}}><Play size={15}/>回看 {asset?.time||'12:34'} 的原话</button><h3>03 下一场改进</h3><ul><li>开场先讲清楚一个具体问题，缩短背景铺垫。</li><li>每段方法讲解后安排一次互动，给家长反馈的机会。</li><li>用小行动收尾，避免笼统的效果承诺。</li></ul><div className="callout"><Info size={18}/>以上为示例内容，话术判断不代表实际停留或成交效果。</div></article><aside className="panel report-outline"><h3>复盘进度</h3><p>候选话术 {assets.length} 条</p><p>待审核 {pending} 条</p><Link className="button primary full" to="/reviews">审核话术</Link><Link className="button full" to="/plans">安排下一场备播</Link></aside></div>}
{tab==='评分（待配置）'&&<Empty title="评分规则待确认" description="当前不预设维度、权重和综合分。你可以先查看复盘结论与原话来源。" action={<Button onClick={()=>setTab('复盘报告')}>查看复盘报告</Button>}/>}
{tab==='候选话术'&&<div className="candidate-list">{assets.map(a=><button className="candidate-row" key={a.id} onClick={()=>{setSelected(a.id);setTime(a.seconds);setTab('录像与逐字稿')}}><div><Badge tone="teal">{a.category}</Badge><p>{a.quote}</p><small>{a.time} · {a.host}</small></div><Badge tone={a.status==='pending'?'amber':'green'}>{{pending:'待审核',approved:'已入库',rejected:'不入库',withdrawn:'已撤回'}[a.status]}</Badge><ArrowRight size={18}/></button>)}</div>}</> }</>}
