import {Routes,Route,Link} from 'react-router-dom'
import {Shell} from './components/Shell'
import {Empty} from './components/UI'
import {Dashboard} from './pages/Dashboard'
import {LiveSessions} from './features/sessions/LiveSessions'
import {LiveSessionDetail} from './features/sessions/LiveSessionDetail'
import {Sessions} from './pages/Sessions'
import {SessionDetail} from './pages/SessionDetail'
import {Weekly} from './pages/Weekly'
import {Reviews} from './pages/Reviews'
import {Library} from './pages/Library'
import {Plans} from './pages/Plans'
import {PlanEditor} from './pages/PlanEditor'
import {Reports} from './pages/Reports'
import {Settings} from './pages/Settings'
export default function App(){return <Routes><Route element={<Shell/>}><Route index element={<Dashboard/>}/><Route path="sessions" element={<LiveSessions/>}/><Route path="sessions/:id" element={<LiveSessionDetail/>}/><Route path="demo/sessions" element={<Sessions/>}/><Route path="demo/sessions/:id" element={<SessionDetail/>}/><Route path="reports" element={<Reports/>}/><Route path="weekly" element={<Weekly/>}/><Route path="reviews" element={<Reviews/>}/><Route path="library" element={<Library/>}/><Route path="plans" element={<Plans/>}/><Route path="plans/:id" element={<PlanEditor/>}/><Route path="settings" element={<Settings/>}/><Route path="*" element={<Empty title="页面不存在" action={<Link className="button" to="/">返回工作台</Link>}/>}/></Route></Routes>}
