import type {State,Asset,Section} from './types'
export const quote='先别急着给孩子贴标签，我们先看他卡在哪一步。'
const base:Omit<Asset,'id'|'quote'|'category'|'status'>={sessionId:'s1',host:'大魏',date:'2026-10-03',time:'12:34',seconds:754,why:'先回应家长的情绪，再把注意力转向具体问题。让沟通从评价孩子，转为一起寻找可执行的下一步。',condition:'家长表达焦虑，或对孩子作出负面评价时。',caution:'先听完问题，不把共情变成对效果的承诺。',adapted:'先不急着下结论，我们一起找出最难的那一步。',favorite:false,learned:false,adopted:false}
export const defaultSections=():Section[]=>['开场留人','痛点共鸣','方法讲解','互动答疑','产品承接','结束回顾'].map((title,i)=>({id:crypto.randomUUID(),title,minutes:i===0?3:5,goal:i===0?'让家长明确今晚能解决什么问题':'',html:i===0?'<p>各位家长晚上好。今天我们先聊一个很具体的问题：孩子开始写作业前，总要拖很久，该怎么办？</p><p>先不急着说他不自觉。我们一起看看，他到底卡在哪一步。</p>':i===2?'<p>先把任务拆成孩子能独立完成的一小步。</p>':i===3?'<p>请家长分享今晚最想解决的问题。</p>':i===5?'<p>今天先尝试一个小改变，下次一起回顾。</p>':'',prompt:i===0?'请家长在评论区说出最常见的卡点。':'',assetIds:i===0?['a1']:[]}))
export function initialState():State {return {
 sessions:[{id:'s1',title:'家庭教育答疑',host:'大魏',date:'2026-10-03',platform:'视频号',duration:'56:20',status:'review'},{id:'s2',title:'学习习惯培养',host:'大魏',date:'2026-10-01',platform:'视频号',duration:'48:12',status:'complete'},{id:'s3',title:'新学期家长沟通',host:'小林',date:'2026-09-30',platform:'抖音',duration:'42:08',status:'prepared'},{id:'s4',title:'陪孩子找到自己的节奏',host:'大魏',date:'2026-09-29',platform:'视频号',duration:'51:36',status:'complete'}],
 assets:[{...base,id:'a1',quote,category:'用户痛点',status:'approved',learned:true},{...base,id:'a2',quote:'很多时候，孩子不是不想学，而是方法不对。',category:'用户痛点',status:'approved',host:'小林',sessionId:'s3',date:'2026-09-30',time:'08:17',seconds:497},{...base,id:'a3',quote:'家长的焦虑很正常，但也会无形中传递给孩子。',category:'用户痛点',status:'approved',sessionId:'s2',date:'2026-10-01',time:'06:21',seconds:381},{...base,id:'a4',quote:'成绩只是一个结果，更重要的是找到问题的原因。',category:'用户痛点',status:'approved',sessionId:'s4',date:'2026-09-29',time:'10:05',seconds:605},{...base,id:'a5',quote:'今天只聊一个问题，孩子写作业拖延，第一步可以怎么做？',category:'开场留人',status:'approved',sessionId:'s2',seconds:40,time:'00:40'},
 ...[quote,'你最担心孩子的哪一个习惯？我们从这里开始。','先做一道会的题，让孩子找回开始的感觉。','把今晚的方法用一次，再看看哪里需要调整。','如果你也遇到过，可以把具体情形说给我听。','一位家长和孩子约定，每天先一起整理桌面。','需要完整的练习步骤，可以看这份家庭练习清单。','先了解适不适合你家，再决定是否使用。'].map((q,i)=>({...base,id:'p'+i,quote:q,category:['用户痛点','互动引导','开场留人','互动引导','互动引导','案例信任','产品承接','成交推动'][i],status:'pending' as const,seconds:754+i*120,time:i===0?'12:34':`${12+i*2}:34`}))],
 plans:[{id:'plan1',title:'家庭教育答疑',host:'大魏',date:'2026-10-05',status:'draft',sections:defaultSections()}],workspace:'直播复盘',reportDrafts:{},weeklyNotes:'下周优先压缩开场铺垫，用一个具体问题引入；每个方法讲解后安排一次互动。'
}}
export const transcript=[{time:'12:10',seconds:730,text:'很多家长跟我说，孩子一写作业就磨蹭，怎么说都不听，真的很让人着急。'},{time:'12:24',seconds:744,text:'其实我们先别急着批评，可能孩子并不是不想学，而是遇到了一些具体的困难。'},{time:'12:34',seconds:754,text:quote},{time:'12:52',seconds:772,text:'找到具体的问题之后，再和孩子一起想办法，比单纯催促更有效。'},{time:'13:16',seconds:796,text:'比如今天先整理好桌面，再从一道会的题开始，让他有一个能做到的小目标。'}]
